name: DockerBuild And Deploy

on:
  workflow_dispatch: # on button click
  push:
    tags:
      - 'v*'

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: get image name
        run: |
          VERSION=$(cat ./version.txt)
          DOCKER_IMAGE_NAME=$(echo "docker.io/mereith/van-nav:v${VERSION}")
          ALI_IMAGE_NAME=$(echo "registry.cn-beijing.aliyuncs.com/mereith/van-nav:v${VERSION}")
          DOCKER_IMAGE_NAME_LATEST=$(echo "docker.io/mereith/van-nav:latest")
          ALI_IMAGE_NAME_LATEST=$(echo "registry.cn-beijing.aliyuncs.com/mereith/van-nav:latest")
          echo ${VERSION}
          echo "::set-output name=DOCKER_IMAGE_NAME::$DOCKER_IMAGE_NAME"
          echo "::set-output name=ALI_IMAGE_NAME::$ALI_IMAGE_NAME"
          echo "::set-output name=DOCKER_IMAGE_NAME_LATEST::$DOCKER_IMAGE_NAME_LATEST"
          echo "::set-output name=ALI_IMAGE_NAME_LATEST::$ALI_IMAGE_NAME_LATEST"
        id: image-name
      - name: Build image And Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.image-name.outputs.DOCKER_IMAGE_NAME }}
            ${{ steps.image-name.outputs.ALI_IMAGE_NAME }}
            ${{ steps.image-name.outputs.DOCKER_IMAGE_NAME_LATEST }}
            ${{ steps.image-name.outputs.ALI_IMAGE_NAME_LATEST }}
